### ISSUE TITLE
Ideas? - Do we drop transaction fee in favor of gas?

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#100]
If semux can do 166+ TPS (for standard transactions)

should we drop the flat transaction fee in favor of gas?

at 5000000 current fee for transfer, and 21000 gas price for transfer, it would imply that 238nSem per gas would give us parity, and we could safely drop flat fee in favor of gas for transfers/votes

How should a validator decide what to put into a block?  Should 'idle' gas rate hover around 238?  less?

Currently sem is around 67c-75c each.  at 0.005 sem, 238nSem/gas is $0.003, less than eth by half, but we are young, and our blocks are empty.

If blocks continue to be empty, should we put a lower limit on gas price? 
Should we allow validators to decide on their own what the lowest gas they'll accept is?
How should dPOS work with gas prices?  On one point, if i have a huge server, i should be free to suck up any mempool things that weak validators can't process.  And if I have a weak validator, i should only take the top X transactions to maximize what I can process and propose in the little amount of time I have to propose a block.

All ideas are open at this point.  Let's figure out what makes sense.

**Comment by honeycrypto** [comment]
I am for dropping flat fee for all VM calls. But can we somehow give the highest priority for regular transactions: send, vote and unvote? I mean if there is vote/unvote, validator must include them and only then process some vm calls if possible.

**Comment by orogvany** [comment]
I'd argue that order should be transfer > vm > votes.  But even that doesn't really make sense in that the validator should maximalize profits for the block.  If I want to pay 10sem to get my contract through, why would a validator process a 0.005 fee sem transfer instead?

**Comment by orogvany** [comment]
Another open point is if I have 2 txs from one address.  
Nonce0 - fee 0.005
Nonce1 - fee 10sem

And there's another account with fee=0.006

And we have to order and pick 2.  We should probably consider taking the 0.005 and 10, rather than just sorting blindly by tx fee alone

**Comment by orogvany** [comment]
Thanks.  so how should gas price be determined?

**Comment by orogvany** [comment]
Have removed tx fees for VM calls in favor of gas
