### ISSUE TITLE
Proposal: remove 'import accounts from backup file' feature

### ISSUE THREAD

**Issue by honeycrypto** [semuxproject/semux-core#105]
I think at first launch we need to provide only 2 options: 
- create new wallet 
- restore wallet from `seed` 

If user has legacy `wallet.data` file, he can just put it manually in wallet folder. 

The issue is that I generated HD seed, created many accounts and transactions. Then I tried to create a wallet in a new location by importing accounts from wallet.data via GUI. But at this point wallet generated a new HD seed and forced me to use it (different from the old one).  

So now, after recovering wallet via GUI + wallet.data, I have 2 HD seeds and the old one can restore only old used addresses, while the new one only new created addresses. 
This is super confusing with many HD seeds for the same wallet.data and very likely this will lead to loss of funds sooner or later.

**Comment by orogvany** [comment]
We might just need to update our wording to user.  Import wallet from backup should import accounts as well as scan for hd accts from that key, but it should *not* replace the current wallets seed phrase.  It's an import/merge feature, not a restore feature.

**Comment by orogvany** [comment]
Fixed.  We still allow import/recover, but we do not replace the existing HD seed.  we just import the addresses from it with a different prefix.
