### ISSUE TITLE
Password Requested on wallet without a password

### ISSUE THREAD

**Issue by Michail1** [semuxproject/semux-core#107]
Hi there,

#### System information
Semux version: `e.g., v1.5.0-rc.1`
OS & Version: `e.g., Windows 10`

#### Expected behaviour

Description
Start client without a password still requests a password.

If a wallet has no password set (nevermind the security problem this imposses), the client still requests a password.  So, a user might waste time and worry about having lost a password that was never set.

#### Actual behaviour

Client requests password.

#### Steps to reproduce the behaviour

1. Start the client using a wallet without a password set.

**Comment by orogvany** [comment]
#108 fixes this
