### ISSUE TITLE
Transaction stuck due to low gas

### ISSUE THREAD

**Issue by mdodong** [semuxproject/semux-core#110]
Semux transaction gets stuck if you use very low gas. If you send other transaction after this even with enough gas, the transaction will get stuck as well. 

#### System information

Semux version: `1.5.0-RC1-021d510`

OS & Version: `Windows 10`

#### Expected behaviour

Transaction will fail if insufficient gas is supplied, gas will be consumed and will allow you to send other transaction

#### Actual behaviour

Transaction will be accepted by the TransactionManager
account nonce will increase
no validator will pickup the transaction
if you send another transaction, it will get stuck
account nonce will increase

- tried resending the transaction reusing the old nonce to overwrite the low gas but get error invalid Nonce
- close and reopen wallet and now getting 
`09:01:05.917 INFO     SemuxBft         Entered validate: proposal = true, votes = [0, 1] [0, 0] [0, 0]
09:01:05.918 WARN     Block            Transaction result does not match for TransactionResult [code=INVALID_NONCE, returnData=, # logs=0]
09:01:05.918 WARN     SemuxBft         Invalid transactions`

#### Steps to reproduce the behaviour

> getPendingTransactions

{
  "success" : true,
  "message" : "successful operation",
  "result" : [ {
    "hash" : "0x676fee4fe62a7adc09818a3b02994443fd1f7d28d9d1f6a7717939cf8f2264a6",
    "type" : "CALL",
    "from" : "0x25291f9f681868ab7f70f0bb58f024e3ee086c01",
    "to" : "0x6b8e0e12f51a98c0c4c5990c3876686329785e65",
    "value" : "0",
    "fee" : "5000000",
    "nonce" : "2",
    "timestamp" : "1542847211654",
    "data" : "0xa9059cbb0000000000000000000000006b8e0e12f51a98c0c4c5990c3876686329785e6500000000000000000000000000000000000000000000000000000000000003e8"
  }, {
    "hash" : "0x27570c94a895c5105ae50c02debed6a9bead6c095a2ceeebc34c10f3e2240fea",
    "type" : "CALL",
    "from" : "0x25291f9f681868ab7f70f0bb58f024e3ee086c01",
    "to" : "0x25291f9f681868ab7f70f0bb58f024e3ee086c01",
    "value" : "0",
    "fee" : "5000000",
    "nonce" : "3",
    "timestamp" : "1542847422855",
    "data" : "0x70a082310000000000000000000000006b8e0e12f51a98c0c4c5990c3876686329785e65"
  }, {
    "hash" : "0x5c714a521da8ab9424a2dbd3887f6943615a8491b3b91cf94aec826690d5f25f",
    "type" : "CALL",
    "from" : "0x25291f9f681868ab7f70f0bb58f024e3ee086c01",
    "to" : "0x25291f9f681868ab7f70f0bb58f024e3ee086c01",
    "value" : "0",
    "fee" : "5000000",
    "nonce" : "4",
    "timestamp" : "1542847602367",
    "data" : "0x70a082310000000000000000000000006b8e0e12f51a98c0c4c5990c3876686329785e65"
  }, {
    "hash" : "0x30a72a57d6760f5b0af126b71a10eab7feed470faaa91be264d7ee30d89c97b7",
    "type" : "TRANSFER",
    "from" : "0x25291f9f681868ab7f70f0bb58f024e3ee086c01",
    "to" : "0xe5f0adab7559cc3920ce454bd32410cbf82f96bd",
    "value" : "10005000000",
    "fee" : "5000000",
    "nonce" : "5",
    "timestamp" : "1542847729529",
    "data" : "0x"
  } ]
}

**Comment by mdodong** [comment]
Restarting the wallet cleared the pending transaction but still getting 
`09:25:49.733 WARN     Block            Transaction result does not match for TransactionResult [code=INVALID_NONCE, returnData=, # logs=0]
09:25:49.733 WARN     SemuxBft         Invalid transactions`

- deleted the wallet and importing the validator address back to a newly generated shows the same error
- transactions are no longer stuck but still shows the `Invalid transactions` in the terminal

**Comment by orogvany** [comment]
It will clear after a few hours.  Thanks for the report!

**Comment by orogvany** [comment]
Fixed in #113
