### ISSUE TITLE
Semux might be prone to Sybil Attack

### ISSUE THREAD

**Issue by argoncoindev** [semuxproject/semux-core#116]
Due to the bearish price movements of cryptocurrencies, Semux stakers have been constantly unvoting and cashing out Semux coins to cover their losses or spendings which leads to decreasing number of staked coins and increasing risk of Sybil attack. If the bear market continues for another 2 years, the price of Semux coin may continue to decline and it will eventually become cheap enough for an attacker to freeze or even take over the network.

**Comment by orogvany** [comment]
How so?  Sybil attack does nothing for an attacker.  They'd still need to control >33% of voted coins to affect network and could do so from just one acct.  No benefit to being 1 or 300 accts

If sales continue to happen, presumably the new owners would stake too, so voted amounts should not diminish.  We have a huge pool population.  Better attack might be pool flooding with 0 fees to gain control

**Comment by orogvany** [comment]
Please feel free to reopen if you have additional information, or if I'm missing something obvious. 

Thanks!
