### ISSUE TITLE
Unable to launch with OpenJDK 11

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#119]
After a fresh OpneJDK 11 installation, I was unable to launch the wallet client. No error message was displayed or logged.

After some trial-and-error, I found the failure is a result of unexpected outputs from the parameter generator program.
```
java -cp semux.jar org.semux.JvmOptions --cli
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
 -Xmx2652m -Dlog4j2.garbagefreeThreadContextMap=true -Dlog4j2.shutdownHookEnabled=false -Dlog4j2.disableJmx=true --add-opens=java.base/sun.net.dns=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
```

**Comment by semuxgo** [comment]
The above message is from `slf4j-api` repository

https://github.com/apache/logging-log4j2/blob/3acea6c6d566d8f54da45651dbf37c1ea3967ef3/log4j-api/src/main/java/org/apache/logging/log4j/util/StackLocator.java#L58-L87

**Comment by orogvany** [comment]
Yeah. I've seen this too. Pretty easy fix Iirc.

**Comment by orogvany** [comment]
Closing due to #120 being merged.
