### ISSUE TITLE
Where are pgp signatures?

### ISSUE THREAD

**Issue by Robespeler** [semuxproject/semux-core#121]
Where are pgp signatures?
This is open source product and this is crypto product. PGP signatures and developer public keys must be available and desirable in many clear ways and sources (gitgub, pgp servers, reddit etc)

**Comment by orogvany** [comment]
PGP signatures are now part of our standard release policy.

https://github.com/semuxproject/semux-core/releases/tag/v1.5.1RC2

PGP sigs included, and my pgp signature is on my github profile.  We do still need to make them more available in other locations, like the semux website, but github as a source is a start.

Thanks for the suggestion!!
