### ISSUE TITLE
Semux Has An Unreasonably High Inflation Rate

### ISSUE THREAD

**Issue by argoncoindev** [semuxproject/semux-core#124]
After reviewing a few successful crypto projects, Semux's inflation rate appears to be unreasonably high in comparison to others which may be the major factor that suppresses its value. The community might want to improve Semux's economic model for the project's sustainability by reducing its inflation rate.

| Coin Name | Current Supply | Per Annum Block Reward | Per Annum Inflation Rate                |
|-----------|----------------|------------------------|-----------------------------------------|
| Semux     | ~9,000,000     | ~3,153,600             | ~35%                                    |
| Ethereum  | ~100,000,000   | ~4,204,800             | ~4% (Casper PoS will introduce ~0.5-2%) |
| Bitcoin   | ~17,400,000    | ~788400                | ~4%                                     |
| EOS       | ~900,000,000   | 48,545,000             | ~5%                                     |

**Comment by honeycrypto** [comment]
At current price that's only $0.20 * 3.15mil = $630K USD yearly or $1700 USD daily. Looks extremely undervalued anyway. 
Even at $1 per SEM that will be only $8600 per day, which is a dust in crypto space. While high inflation may help to improve distribution and provide a higher availability of SEM coins. 
Currently there are only 1.3mil coins spendable out of 9mil available supply, this is not good for the liquidity in a long run.

**Comment by argoncoindev** [comment]
@honeycrypto Locked coins are liquidity assets as well if Semux doesn't impose any limitation to unvoting. A real life example is that people can unvote and sell the unvoted coins within 10 minutes. The locked coins are not really locked in any way.

**Comment by orogvany** [comment]
This is kinda silly math.  In it's first year, bitcoin had an inflation rate of infitite,from 0 to whatever, like every coin in existence.

As coins grow, there's more out there so percent of inflation is always a moving target.

Comparing with coins already mature enough to have had halvenings isn't ideal.

But setting block reward to 0.3 sem, or 8.64 sem per day validator only get 259sem per month.  I think that would encourage not validating, or trying to skimp on hardware for validators..  it's an interesting idea, but it would fairly drastically change how pools and validators function and choose to validate.  I'm not sure people would spend $50 a month to run a 5% fee pool for 12 sem per month.

**Comment by argoncoindev** [comment]
@orogvany 

> As coins grow, there's more out there so percent of inflation is always a moving target.

It can be easily calculated that the inflation rate will still be high after 10 years as the following:


Year | Supply | Blockreward | Inflation
-- | -- | -- | --
2019 | 9,000,000.00 | 3,153,600.00 | 35.04%
2020 | 12,153,600.00 | 3,153,600.00 | 25.95%
2021 | 15,307,200.00 | 3,153,600.00 | 20.60%
2022 | 18,460,800.00 | 3,153,600.00 | 17.08%
2023 | 21,614,400.00 | 3,153,600.00 | 14.59%
2024 | 24,768,000.00 | 3,153,600.00 | 12.73%
2025 | 27,921,600.00 | 3,153,600.00 | 11.29%
2026 | 31,075,200.00 | 3,153,600.00 | 10.15%
2027 | 34,228,800.00 | 3,153,600.00 | 9.21%
2028 | 37,382,400.00 | 3,153,600.00 | 8.44%
2029 | 40,536,000.00 | 3,153,600.00 | 7.78%

> I'm not sure people would spend $50 a month to run a 5% fee pool for 12 sem per month.

The price is also a moving target that will likely increase when the inflation rate decreases based on the observation to block reward halving event of Bitcoin.

**Comment by orogvany** [comment]
You are also not accounting for founder, community, or development.  If you include those, this year is only 10% not 35%

**Comment by orogvany** [comment]
I'll take a look and compare it against actual comps, rather than 10 year in projects, and see.

Thanks for bringing it up

**Comment by argoncoindev** [comment]
> You are also not accounting for founder, community, or development. If you include those, this year is only 10% not 35%

Why don't you take those 3 accounts into account of circulating supply on CMC and the explorer if that's the case? Aren't the top 3 accounts supposed to be locked? I am confused.

![selection_035](https://user-images.githubusercontent.com/33402551/51293749-1c3add80-1a4b-11e9-93f4-04f43cc4faae.png)

![selection_036](https://user-images.githubusercontent.com/33402551/51293803-5ad09800-1a4b-11e9-8131-7b0a8366064b.png)

**Comment by argoncoindev** [comment]
> You also aren't accounting for semuxs own halvening in a few years

The supply won't be halved even after 9 years. It will be reduced by 33% according to this piece of code:

https://github.com/semuxproject/semux-core/blob/40a00ccdace0f5ff5fe82b86e9a660f5ca758f39/src/main/java/org/semux/config/AbstractConfig.java#L159-L169

Bitcoin's block reward halves every 4 years. Ethereum's developers have cut the reward from 5 to 2 since 2015 and they've decided to cut it further down once PoS implemented.

![dmr52bzucaazt5t](https://user-images.githubusercontent.com/33402551/51294221-fb738780-1a4c-11e9-863d-fa2b00b66a82.jpg)
![controlled_supply-block_reward_halving](https://user-images.githubusercontent.com/33402551/51294240-11814800-1a4d-11e9-8ed7-c76974aef408.png)

**Comment by orogvany** [comment]
You are correct @argoncoindev Thanks for clarification, my memory was wrong on that.

I'd certainly be in favor of more aggressive reduction of rewards as time goes on, it's easy to adjust and fix.

So, what's the proposal here?  I think dropping the current 3 SEM now without warning is not likely to garner any friends ;). And I don't believe that the current 30% is necessarily problematic, as POS with pools really just means that SEMs are more common than they were, and users are not losing value.

Is it inflation if you start the year with 100 SEM, and at end of year you have 133 SEM?  You still own 0.0004% or whatever of the coin in circulation, so nothing has really changed except the expected price.

But I agree a more aggressive dropping of forging rewards may be worth considering.

As to why CMC does not take those addresses into consideration, it's by their definition of market cap.  They use something similar to stock float, where assets held by the corporation are not included in public valuation.  Honestly, the whole market cap thing is a bit of wonky anyway.  Coins can't be worth the full value of all shares by price, if there's only liquidity for $10,000 out of 50 million, but as long as they're consistent, sure.  

But, if the main dev decided to take the remaining 5 million sem in the community account and evenly distribute them to all users, this too would have effect that forging inflation would be a lower percent, so it too is an option (one I don't think we're considering at the moment).

**Comment by argoncoindev** [comment]
A quick proposal is to halve block reward every month over the 3 months after a fork. By reducing the reward gradually delegates will have enough time to become aware of the change and the inflation rate of ~5% can be achieved within a matter of months. 

Month | Block Reward | Inflation Rate
-- | -- | --
Fork | 3 | 35.04%
Fork + 1 | 1.5 | 17.52%
Fork + 2 | 0.75 | 8.76%
Fork + 3 | 0.375 | 4.38%

After the fork, I'd suggest the project to consider a more sophisticated system that allows the inflation rate to be adjusted dynamically like Casper. This dynamic system solves the liquidity issue by reducing the inflation rate when there are too many staked coins and vice versa.

<img width="748" alt="ethereum-hybrid-casper-rewards 3" src="https://user-images.githubusercontent.com/33402551/51298822-105a1600-1a61-11e9-9c3f-54b350c1b024.png">

**Comment by honeycrypto** [comment]
@argoncoindev we moved further discussion here: https://github.com/semuxproject/RFPs - see RFP-002. Your proposals are welcome.

**Comment by orogvany** [comment]
This has been addressed in 1.4 release. Thanks!
