### ISSUE TITLE
custom.properties file instead of touching semux.properties

### ISSUE THREAD

**Issue by witoldsz** [semuxproject/semux-core#128]
#### Background:
As of now, the `semux.properties` file must be modified to change some settings, like enabling API, changing port numbers, etc…

#### Issue:
It is quite annoying to update the node because of that, because one has to re-apply the changes on each Semux upgrade. It is not safe to overwrite the `semux.properties` file, because new version can provide some new properties or can change some defaults (like it was when upgrading my testnet validator from 1.3.x to 1.5.x).

#### Solution:
Introduce another file, e.g. `custom.properties` where users can create/overwrite values from `semux.properties`. On each new upgrade, one would just copy the `custom.properties` over to new location.

I can develop it, just need the green light.

**Comment by witoldsz** [comment]
Version 1.5 has EVM related properties, they are not present in 1.3.

**Comment by witoldsz** [comment]
> They should all have reasonable defaults set.

I'm not sure I understand: ale the properties declared in the `semux.properties` have defaults hardcoded in the Semux node? That means I can wipe the file out, reduce it to 0 and everything should work fine?

**Comment by orogvany** [comment]
There are a few properties that are required like p2p seed nodes, but all the new properties we are adding have defaults.  So yes, you should be able to delete most of the properties in the file and it'll continue to work

We only expect that on upgrade that old configs should still work without changes.  Check out the AbstractConfig class.  If we missed setting a default for VM feature that would be a bug

**Comment by witoldsz** [comment]
If that is the case, then I am closing this issue. From now on I will just overwrite `semux.properties` on upgrades.
