### ISSUE TITLE
Console window does not support parameters with spaces/quotes

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#13]
As you can use the API to create/interact with items requiring spaces (signMessage, etc)
The console window should support tokenizing based on quoted blocks of text

We should also support escaped quotes, so signMessage `"hello \"world\""` should parse

**Comment by semuxgo** [comment]
Any plan on improving this?

**Comment by orogvany** [comment]
Yes, this kinda fell off my radar

**Comment by orogvany** [comment]
#203 merged, fixed.
