### ISSUE TITLE
API v2.2 is not compatible with v2.1

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#145]
Some of the endpoints have been updated to include VM results. Not sure if these changes will affect clients, especially exchanges.

**Comment by orogvany** [comment]
Hm. We can filter transactions not matching types. Are you suggesting we also clear new fields like block.gasused?

**Comment by witoldsz** [comment]
Introducing VM could be a good opportunity to bump API to v3… That could also allow for a change to make a more clear distinction which endpoints are tied to node's wallet/private keys and which are not (useful for open API gateways like https://api.semux.online and, in general, to Semux API integrators).

**Comment by semuxgo** [comment]
After some investigation, I think we should probably keep the existing endpoints untouched. I'd also propose to add new endpoints to support VM functionalities:
- `/transaction/call` for CALL transactions
- `/transaction/create` for CREATE transactions
- `/receipt` for retrieving transaction receipts

These changes are non-intrusive, so we can either continue with 2.2 or jump to 3.0

**Comment by orogvany** [comment]
I think those endpoints exist already...

We may want to move call local into it's own call so API gateways can more easily support local calls

**Comment by orogvany** [comment]
Think this can be closed
