### ISSUE TITLE
Testnet Reset With a New Set of Premine Addresses

### ISSUE THREAD

**Issue by cryptokat** [semuxproject/semux-core#166]
According to @semuxgo some of the testnet premine private keys are lost and unrecoverable. Reset of the testnet will be required for #160 to proceed.

If you want to work with testnet with a premine in the future, please leave your testnet address and its ed25519 public key below.

**Comment by honeycrypto** [comment]
How can I retrieve ed25519 pub/priv keypair from my testnet wallet.data?

**Comment by cryptokat** [comment]
@honeycrypto 
Generating a new one is the only way without modifying the code afaik:
![Selection_059](https://user-images.githubusercontent.com/32390172/58438733-eeedf280-8102-11e9-89a3-177b73883c50.png)

**Comment by honeycrypto** [comment]
ok thanks @cryptokat 
```
cb3b1a71e842d8b3a6c7137fdda9fc991b14f4e1
302a300506032b6570032100358fe04653e3364f7851d9d94d118e2e09a2add75722180017ecfef606ce5e68
```
This one will be used for Testnet Faucet. I think that's enough and we can proceed, so everyone else will be able to claim testnet coins here: https://www.semux.org/testnetfaucet 

Overall, I do support the idea of launching Testnet 2. Its blockchain is huge already and people have to download archives shared via discord. I think it's a good practice to reset testnet every year.

**Comment by honeycrypto** [comment]
Maybe we can also decrease number of validators to 5-10, now we have 15 iirc. We had problems with network getting stuck when someone register delegate and closes his wallet.

**Comment by semuxgo** [comment]
I have two nodes, and below are the public keys:
```
0x302a300506032b6570032100fdd012156d14623082633b18a4d342cd37f07af3c5696e11a0947ab0e0bf7e00
0x302a300506032b6570032100dca9f23f1a1d24972697e7ae17b19557e6d8c21fd3a115757ad85a84293dd5de
```

**Comment by orogvany** [comment]
0x302a300506032b6570032100c91464ea6062350e56c980c4bd5b3f183e3b39179b16a84b123e6f077db1eb70

**Comment by semuxgo** [comment]
Faucet key has been replaced with 
```
fe81ddefe30d7ab28f2ce73bb37d3d42603c4ddf
302a300506032b6570032100762f583ff654a56040fbcacca0a434f0e23da726bf6750641bac28a16f500691
```

**Comment by orogvany** [comment]
This is done.
