### ISSUE TITLE
Unable to sync testnet

### ISSUE THREAD

**Issue by victorx716** [semuxproject/semux-core#170]
**Description**

I was not able to sync my testnet after downloading the latest release and executing './semux-gui.sh --network testnet'. It is stuck at block 681k. 

Tried it again with a a fresh download, same result.

#### Steps to reproduce the behaviour

1. Download latest release
2. Execute './semux-gui.sh --network testnet' and create new wallet, then stops at block 681k.

<img width="652" alt="Screen Shot 2019-06-26 at 5 53 02 PM" src="https://user-images.githubusercontent.com/38618788/60229460-97ef5080-985b-11e9-989f-bf2aea1bc539.png">
<img width="899" alt="Screen Shot 2019-06-26 at 5 42 48 PM" src="https://user-images.githubusercontent.com/38618788/60229461-97ef5080-985b-11e9-967d-1a7d6971f3bf.png">

**Comment by orogvany** [comment]
Are you using 1.5 rc2 for testnet?

**Comment by victorx716** [comment]
That solves it. Was using v1.4. Thanks @orogvany
