### ISSUE TITLE
Re-enable HD wallet with Ledger support

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#171]
There are currently two specifications for ed25519 HD. 
- SLIP-0010, https://github.com/satoshilabs/slips/blob/master/slip-0010.md
- BIP32-ED25519, https://cardanolaunch.com/assets/Ed25519_BIP.pdf

**Comment by semuxgo** [comment]
Based on limited survey, both specs are being used.

Ledger started to support `BIP32-ED25519` since the 1.5.5 firmware, as reported in https://www.ledger.com/ledger-releases-a-new-nano-s-firmware-update/.

SLIP-0010 has been used by various projects, see the dependent projects  https://github.com/alepop/ed25519-hd-key/network/dependents

**Comment by semuxgo** [comment]
A reference implementation of BIP32-ED25519 has been made available by Ledger at https://github.com/LedgerHQ/orakolo/blob/master/src/python/orakolo/HDEd25519.py

**Comment by orogvany** [comment]
Would like to consider this for Milestone 1.5.0

**Comment by iamyulong** [comment]
Key recovery attack on BIP32-Ed25519, Web3 Foundation

https://forum.web3.foundation/t/key-recovery-attack-on-bip32-ed25519/44

**Comment by semuxgo** [comment]
See #231
