### ISSUE TITLE
InternalTransactions fail to store correct value

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#187]
After the change to use wei, values often exceed Long.max

When we persist the TransactionResult, this often overflows, and stores the wrong value.

Thankfully, I used devnet, so i dont think i broke testnet2 already, but fixing this will break testnet without fork.

It's also slightly odd that values are interpreted as wei in contracts, so if i want to send 100 sem within a contract, I need to do
```
  byte[] method = HashUtil.keccak256("transfer(address,uint256)".getBytes(StandardCharsets.UTF_8));
        byte[] methodData = ByteArrayUtil.merge(Arrays.copyOf(method, 4),
                DataWord.of(to).getData(), DataWord.of( new BigInteger("100000000000000000000")).getData());
```
instead of 100000000000 as I would expect.

If I retrieve internal transaction for the above, I get (converted wei to sem)
```
{
  "success" : true,
  "message" : "successful operation",
  "result" : {
    "blockNumber" : null,
    "logs" : [ ],
    "returnData" : "0x",
    "gasUsed" : "30986",
    "code" : "SUCCESS",
    "internalTransactions" : [ {
      "type" : "CALL",
      "from" : "0x5c92355fddd7639ecf6f5bfdaee33e62e808aa3c",
      "to" : "0x64d04522b749b44b1bf0e1afffdd99ef2b826861",
      "amount" : "7766279631"
    } ]
  }
}
```
So it breaks on very low sem amounts (<100sem)

**Comment by semuxgo** [comment]
Is the testnet already polluted?  We can apply a hotfix for this if not.

**Comment by orogvany** [comment]
I don't think testnet is yet polluted. I did all my testing in devnet. But I can run a scan to verify

**Comment by orogvany** [comment]
Confirmed not polluted yet as of block 2944
