### ISSUE TITLE
Core: Nodes continue to signal even after the fork has been activated

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#189]
As reported by @honeycrypto.

In the testnet, the VM fork was activated at block 1500. The signal still exists in block 1501

**Comment by orogvany** [comment]
see #139 

Most forks we've had stop syncing for any non updated clients when going past the activation point, so they are forced to update.

The VM fork continues to allow old clients to sync up until the point of first CREATE/CALL (or at least it did on old testnet), so the old clients would eventually stop syncing, update, but would have already missed the signalling.
