### ISSUE TITLE
Improve binary distribution

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#19]
The installation process of semux is not very user friendly.  We may consider distributing native launchers for different platforms.

Reference:
- jlink, https://docs.oracle.com/javase/10/tools/jlink.htm 
- packr, https://github.com/libgdx/packr

**Comment by semuxgo** [comment]
To enable jlink, we may need to re-structure our project to using Java Modular System.

**Comment by orogvany** [comment]
What does jlink enable that we don't get via packr?
I don't see that packr requires jlink.

Java modular system would require some work, I wonder if all of our libs support it yet?  (still ramping up on ins and outs of java modular system)

**Comment by iamyulong** [comment]
We now have pre-built jvm binaries hosted on https://github.com/semuxproject/jvm

Will compare the jlink and packr solutions in a bit

**Comment by orogvany** [comment]
1.4.0 is released, let's move into 1.5.0 or 1.6.0.
