### ISSUE TITLE
Core: State changes of local-call transactions should be discarded

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#205]
calling a precompiled contract when local=true is usually allowed, so there is no check.

However, for the semux precompiled contracts, they need to be within a transaction.

Currently I can call it, and it shows up as me voting for delegate in my local DB, but no other nodes would know about it.. probably breaks my local DB.

We could -> 
* Add something to the context to be able to determine internal/external calls
* add another method to PrecompiledContract interface to denote whether they can be run as local calls.

Let me know which sounds more preferable, and I can implement (or free free to update).  The second seems more extensible, can use default interface methods to return allow local, seems like a more general solution, but open to either.

**Comment by orogvany** [comment]
Some of this has been fixed/mitigated with recent changes in #201 but I'm not sure its sufficient enough.

local calls with API are now gated through not sending a from address nor signature, so this should prevent these contracts from being called due to failure checks if from is not set.

Should cover most cases, but is worth additional eyes.

**Comment by semuxgo** [comment]
I think local call into precompiled contract should be allowed, either by transaction or internal transaction.

**Comment by orogvany** [comment]
Yes. For other precompiled contracts.  But not vote/unvote

Maybe the bug here is that we are committing the repository on internal calls.  Internal calls are not permitted to change state, so we should never commit...

**Comment by semuxgo** [comment]
Good point!

The reason is that the local-call transaction state changes are committed in the pending manager. This is not correct, they should be discarded.

https://github.com/semuxproject/semux-core/blob/19f71512572ee0a6bf6d05ba3c31990b2b9ad29b/src/main/java/org/semux/core/PendingManager.java#L371
