### ISSUE TITLE
Semux Unicode Folder Problem

### ISSUE THREAD

**Issue by levyashin1** [semuxproject/semux-core#24]
I copied my semux folder and put a different name to it with unicode.

![2018-07-17_19-23-26](https://user-images.githubusercontent.com/33433070/42831392-e3d81118-89f6-11e8-86b4-6168f39e0a91.png)

After i started the semux wallet in the new folder, it started to synchronize from the beginning but there was a database folder in it.

So i checked and see, it opened a new folder and create a new database in it.

![2018-07-17_19-24-59](https://user-images.githubusercontent.com/33433070/42831483-22bde07e-89f7-11e8-943c-df9e81fd2e60.png)

Operation system: Windows 10 / 64bit Turkish

**Comment by orogvany** [comment]
can you try adding "-Dfile.encoding=UTF-8" to your semux.bat and see if that works?  (I don't have windows)

Thanks for the report!
