### ISSUE TITLE
Unable to trace vote/unvote operations from smart contract

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#249]
# 🚀 Feature Request

Allow off-line tools to trace vote/unvote operations.

## Motivation

There is currently no way to trace vote/unvote operations from smart contracts. Traditionally, this is addressed by using events in Ethereum. We need something similar for offline tools to process vote/unvote events.

**Comment by witoldsz** [comment]
Not only vote/unvote but also transfers do not appear in transactions history or in blocks view of API.
