### ISSUE TITLE
PGP Signatures

### ISSUE THREAD

**Issue by honeycrypto** [semuxproject/semux-core#256]
Add digital signatures and readme.md instructions to all releases

**Comment by honeycrypto** [comment]
_here is a draft Wiki file about verifying binaries if we want to provide any._

The official Semux releases have signed hashes that you should check to confirm that they are the same binaries that the developers posted. This page provides instructions for that.

In order to verify binaries or other signed files from the Semux Project, there are a couple pieces of software required:

SHA-256 – Once you download your file(s), you need to check their SHA-256 hashes, so you may need to download a tool to do this, depending on your OS.
GnuPG or PGP – This is required to import public keys and verify signatures. Examples below use GnuPG.
The following instructions should work as is on Linux/UNIX/macOS. Windows users will have to install sha256 and gnupg themselves and use the windows cmd terminal to do this. The steps to verify the binaries are as follows:

- Download the file manifest, the signature for the file manifest, and the zip/tarball for your OS [from here](https://github.com/semuxproject/semux-core/releases/latest). 
- Obtain the SHA-256 value for the zip/tarball for your OS and check that it matches the value in the file manifest, e.g. for 64-bit Linux:
```
$ sha256sum semux-linux-2.0.1-34af66c.tar.gz
....REPLACE_ME.... semux-linux-2.0.1-34af66c.tar.gz
```
Compare the value you got in Step One to the value for the file in the manifest file.

Import the Semux Release Signing Key in GnuPG. You will only need to do this a single time and can skip this when verifying later releases on the same computer.
```
$ gpg --keyserver pgp.mit.edu --recv-keys ....REPLACE_ME....
gpg: requesting key ....REPLACE_ME... from hkp server pgp.mit.edu
gpg: /home/user/.gnupg/trustdb.gpg: trustdb created
gpg: key ....REPLACE_ME...: public key "Semux Release <dev@semux.org>" imported
gpg: Total number processed: 1
gpg: imported: 1 (RSA: 1)
```
Verify the signature for the file manifest is valid and created by the Semux Release Signing Key:

$ gpg --verify manifest-20190822.txt.asc
gpg: assuming signed data in `manifest-20190822.txt'
gpg: Signature made Wed 21 Aug 2019 12:16:52 PM UTC using RSA key ID ....REPLACE_ME...
gpg: Good signature from "Semux Release <dev@semux.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg: There is no indication that the signature belongs to the owner.
Primary key fingerprint: ....REPLACE_ME....
Subkey fingerprint: ....REPLACE_ME....

The zip or tarball with binaries for your platform is now verified and you can be confident they were generated by the Semux Project.

**Comment by semuxgo** [comment]
Included GPG signature for the latest releases.

Public Key:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Keybase OpenPGP v1.0.0
Comment: https://keybase.io/crypto

xsBNBF1gAA0BCADJbW4xpPiC+Iy2ysAns2CVrcXNL78Op/BRbRMaPIs4kpiBvgz3
chqbHUXCyo6dmvkA3lzlZru1svrAj29teQeVJU915W2Z7YWlgAvsg4+cE0njWSm7
RfZz3srSyQQOv9Jte4eLhKQTuLPkWlxK5yJ6gP8ZKd3lZAIMy4QHJGZjfaglqwvy
Y8nLQKE37poXMrHqgAu5qZ6Ga02YbecSnJNSfejsVLL7s9KFlC/VBFWEY890wMrq
fgYHJWQMX2qrdqmmbWy1NrgbVAtEGvkQQ7DvbYt0DTEZPn9wvXYoObY+JWOy5oho
3MB1aiqsToEXr6GaNWuHexwxAR5l0GtSP8EvABEBAAHNHVNlbXV4IEFkbWluIDxh
ZG1pbkBzZW11eC5vcmc+wsBtBBMBCgAXBQJdYAANAhsvAwsJBwMVCggCHgECF4AA
CgkQTpHr6lBYcWk8rggArwN96EWnP1Qzrx27Pw1vIfxsx/FHaw1ni6Pc8myVuL/s
gGuK2SuThkz8yvf3et22in0Lp5Y57P1gmHa4y2h3G76UgUe7yl+jJIP3g9BvJm92
+UsUpHc+LAr1KuPfznnkir4YHq0Us3Xbwoi6LCZ+dsG1OCQunISvoTo/z3XATO5t
CWeQW2nAwEMkpwDkmbA0dFkwxXt/ByVZdn8DvDhs827724daNhQOhjngkMp1Y7sk
2pDyuOdHQ/ac+XdCIBwa6U6AS+/52kWQFNSLBd3sMSfUimbjUO3h8eNvr4KBfBL5
wexDFxX5cmKz7PJqxI9fC7hVg4VxlMJoIbWC5UPzBc7ATQRdYAANAQgAvCnhw/ui
N+QAgAlpJdMxRSm7nMNZIfoadocSXHW04b6ql9midxyVhIVNbFWnmyYbQnuIoWQE
kI85l5BGzzdXokDb7PcotkATh4u94qp2HWZL3X0tQyfXjK6O4anQZNk6nPFXF00A
+SnqweXYiEQIlJ9PL2MV8nAjXyU2+UEo7Ca+c0aOEGNCdbi6gnfJuNOh4FPYl/wj
R/JcSHTcZC+JhZGFb1p2felfw3Mm4KWpiQSCjfpjI0ZY1Fjj5e7b1sAl6sK4In8H
IJfcXRpGcq+4S2HUA7p64Zwwx8zr75uZCbqkU4u1w08AMIz0YT7rnOWUYBTzin2B
1ZwQFkc3fHeXRwARAQABwsGEBBgBCgAPBQJdYAANBQkPCZwAAhsuASkJEE6R6+pQ
WHFpwF0gBBkBCgAGBQJdYAANAAoJEDFLEXeNPasRzRoIAKpMI2si5XXMINnM/vhi
RN9ggNr0ouG+BcSuk0nc+S+rT+QUKu7UqpVSaiNMXqLMN5E4H9Cjn0LpwD16dCeS
9AlolvRVCeoESCYcmaZlbU7R8dvWD8XekcDc9EsM0rLi+sAnBB3PscQDQIq3gpcs
ohvsxud63uz2n3u+D8SZOOdei5+u1ivmLtuNqK9XN1Tn9XW/PX/TwIMRhV+JkFMV
d00TzSIWQeSuRcChGOsmMxpyzGBHC7eebNDU3WHUUGX8KykZZPssNLWsu6UzrXeY
U6Hu+I2QrNVq3eWaxEMM41OiZaF5CNpiGgullqecj/y7gxryOFjaScWkEDhQ/pli
OK7QSgf+LVIomm1+hUwtJfJhGYaRspvnIDD9onYqhMRwL94ZEIjGg3w1vqejLSDb
TnTGAVgx4mY3O/lmqnkadZIoly5+yZmEJisCO1XY2fqmXFWoqJHqUfToBOAkXbE6
2bMU2iar7XqhcRmFjzOsZ+zzmDQ+8gPNLxswrn1W9MHqYpJR6mwTGfrj9QaRggQQ
ymN1n4YUAOMh9xSndmQ8K4J6w+6OacBIfHiUC51wNLOsXhAmJushTH7p+lR8eBNE
xYz/i7QDW5NqbDD/pAWq+F/H455vZlIYl1pWDt+vCNJDG6976uOZSXQ7/xh15a6K
dfzIy+nYx4FedjFxzi2cKeAHtnfHuc7ATQRdYAANAQgAwXfSwhmFFKHEQ2n+61VA
VKhSBGUmYu2iiOWxDbWetd2qfGCDidfkXWhOzhRAHi2Khd7hKPVxA1VuecyX1y7M
hwNNls8C/iSyUdC7zSm4x/iJo3mBq1hah0I+pojbr1StD03/IWERT46/6ShI2v8Q
RewrO77KQbTMjKSWFioHZp6WWunUUjhWj/B9kWn+Bdvmh6sTqNPwqg7ITULAz/cM
l+ql6SuFW1gzDufqV+7j/7FNcMaOptrUVbFZc0+z6PdAliCrjfIXTTEbP7m3+BOS
g52XmegFrYz7UDRt0UfSqGy5eTLG0+rgK2b64L+KqomBe39aDkVF+cw42ddsGnwS
xwARAQABwsGEBBgBCgAPBQJdYAANBQkPCZwAAhsuASkJEE6R6+pQWHFpwF0gBBkB
CgAGBQJdYAANAAoJENpvrrW9YvvvOCMIALXMVX9xUNQZuXFMtD/W9snSHGkD9KAc
8cVYsXgpAhx+GFy8Z14sIU9wJRN7mnr1gbPeCq7972URAyyf8ORUDAYroBBw1njI
Ldefx7NkGwo4+KHYY6/HqyMxfRM7W0De+aZuD4Vuaa3lXhEAW908jSY0MhT09vFL
EV8lmBgODHMYFb4EueKKQW+mbbfz4wZiSpAXfd9DnGZWNS/B2GUShgdijvxTZ6Cx
QnfFtROMU6qotzCRmZ+3GbJQxGKrXvHJ54SPJ+QgmC6Mox6T9fZFbWy3z6n8rdG8
oNQ0PjoG7btpe2tLlw9L0wSy2LTv9yKnkQvpsBS+KUVwktau1jmq6weUHQgAs9ZL
1FP1qhxzTMqTQQyToA9Lk08HyGnH9S6W98j9KDsG1u93nfnRN2wIvrGS/qHnuXtu
kjrtefm33jS9bCRnZ6pEGqQ4QdsJBC1o1rETJjMOLw6NpC/kD1ZKQWStLxdT6Aku
w30XzWfj0TL8+81nqN5OhlN9EZeh9LNDF4Poju9XQSmkwpA34wgEIqxLDL9VhsAs
xt1SHvIYi3Q8zN09wkpin56wWnV8N43swT6kOB/HJIIcaPPfr6M/32ONScUIbGlP
YfRBJ7higGQB0Q/HzxhBlctJ5RqpHp3WRvMz19zsXx+ZAfjygNvGEy6iKQa6hvEb
l6a7t7KdQcaXtu2plQ==
=RGaZ
-----END PGP PUBLIC KEY BLOCK-----
```
