### ISSUE TITLE
Vote/Unvote precompiled contracts return success even in case of failure

### ISSUE THREAD

**Issue by honeycrypto** [semuxproject/semux-core#260]
# 🐛 Bug

VM call fails, but the `\transaction-result` still reports `"code": "SUCCESS"`

## To reproduce

1. Send CALL vote with amount larger than current balance 
2. Send CALL unvote to a delegate where you have 0 votes 

## Expected Behavior

`\transaction-result` must return code: FAILURE. In fact, it is out of gas.

**Comment by orogvany** [comment]
Ooo. That's no good.  Prob require softfork for this.  Good catch.

**Comment by semuxgo** [comment]
Will be fixed once the `VOTING_PRECOMPILED_UPGRADE` softfork activates.
