### ISSUE TITLE
New Version Doesn't Start with Unicode Problem

### ISSUE THREAD

**Issue by levyashin1** [semuxproject/semux-core#274]
I am using windows 10 64bit turkish version.

I installed clean latest version. With or without fastsync after entering password nothing happens. Also that may cause from the unicode problem you can see on ss.
![2019-09-17_18-52-13](https://user-images.githubusercontent.com/33433070/65058186-827e5400-d97c-11e9-9343-406ce6826585.png)

**Comment by honeycrypto** [comment]
Please run `semux-gui.bat` if you're on Windows, or `./semux-gui.sh` if you're on Linux or macOS.
