### ISSUE TITLE
devnet not useful for VM development

### ISSUE THREAD

**Issue by witoldsz** [semuxproject/semux-core#276]
The `semux --network devnet` has no forks activated. It's useless for VM development then.

The https://github.com/semuxproject/semux-core/blob/master/docs/Devnet.md says nothing about the issue. Is there any way to activate forks?

**Comment by orogvany** [comment]
Yes. You can activate forks.

The code is there and commented out in DevnetConfig.java iirc

**Comment by orogvany** [comment]
Looks like someone refsctored it and removed the 'just uncomment and go'

But I think you'll find the manuallyActivatedForks() method useful

**Comment by witoldsz** [comment]
I did not say it's impossible. It's just not user friendly. Look how many tools for developing Ethereum contacts are there, easy to start writing, deploying, testing, etc...

How can we attract devs to use Semux if first contact requires tinkering with source and recompiling. 

Some solution should be discussed.

**Comment by witoldsz** [comment]
Maybe the title should be renamed to: devnet not ~~useful~~ friendly for VM development

**Comment by orogvany** [comment]
I guess the 'useless' as you call it devnet is maybe not a good fit for what you are attempting.  Is there a reason testnet isn't viable?  I don't think devnet was ever intended to be of use to developing on top of the platform, but more for developing and testing things where the network needed to be set in a specific change or where a concensus change wouldn't be usable but rest of network.

If you're going to just develop entirely in a bubble, why use a blockchain at all? ;)

The solution as near as I can tell is to support web3js and the like so devs can more easily work with it, but that's already on roadmap...
