### ISSUE TITLE
Testnet stuck with 8/10 validators online and on the latest wallet version

### ISSUE THREAD

**Issue by honeycrypto** [semuxproject/semux-core#277]
# 🐛 Bug

We're already 4 days on block 244,322 with 8 validators connected (v2.1.x) and `view=0`.

**Comment by honeycrypto** [comment]
Looks like in pre_commit some validator rejects block. Validate 7 approvals, Pre-commit 6 approvals. Also i see some "On new_view" messages in the log, but it actually never changes and looks like turn never goes to the next validator.

**Comment by honeycrypto** [comment]
Test network was fixed on 22 October. 

Block 244,322 (08 October) https://testnet.semux.info/explorer/block/244322
Block 244,323 (22 October) https://testnet.semux.info/explorer/block/244323 

That block also included one 2 weeks old transaction. 
Before Testnet got unstuck, validators were voting for 2 competing chains with the different block hashes: 
```
VALIDATE cd70342c6c23e34db9d5a6729973bf9ac5858f5f270bfc9df7efe8363c95c1e5
VALIDATE cd70342c6c23e34db9d5a6729973bf9ac5858f5f270bfc9df7efe8363c95c1e5
VALIDATE cd70342c6c23e34db9d5a6729973bf9ac5858f5f270bfc9df7efe8363c95c1e5
VALIDATE cd70342c6c23e34db9d5a6729973bf9ac5858f5f270bfc9df7efe8363c95c1e5
PRECOMMIT df67715085c9d1a728d8de7a74a9e505e8420cee1a680793634d65e17eb21832
PRECOMMIT df67715085c9d1a728d8de7a74a9e505e8420cee1a680793634d65e17eb21832
VALIDATE df67715085c9d1a728d8de7a74a9e505e8420cee1a680793634d65e17eb21832
VALIDATE df67715085c9d1a728d8de7a74a9e505e8420cee1a680793634d65e17eb21832
```

Also, while the primary validator was `testgost111`, all the further turns within 2 weeks took backup validator `semux02` and he never passed the turn, neither increased the view within 2 weeks.

**Comment by semuxgo** [comment]
I think we should destroy the testnet for now:
- There isn't much activity on testnet and developers can use mainnet for testing purpose with trivial cost
- As a core developer, we should test new features with repeatable integration tests (full CI/CD for faster iteration)

And we can alway come back if a strong demand arises.
