### ISSUE TITLE
run semux as daemon in ubuntu

### ISSUE THREAD

**Issue by amazingMan2017** [semuxproject/semux-core#281]
# 🚀 Feature Request
Hi all , I get a cloud server installed ubuntu and connected it  over ssh protocol , I run ./dist/linux/semux-cli.sh in foreground. but how can i run semux as a daemon in background?

**Comment by orogvany** [comment]
https://github.com/semuxproject/semux-core/blob/master/docs/Full-Node-Setup.md

Check at the bottom for systemd setup

**Comment by amazingMan2017** [comment]
ok ,thanks
