### ISSUE TITLE
Need URL for total supply

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#29]
To get listed on sites like coinmarketcap, we need to supply a link to a page that just supplies the total supply

e.g.
https://dogechain.info/chain/Dogecoin/q/totalbc

Let's get this going, as CMC just removed min volume requirements.

**Comment by borderline23** [comment]
here there is https://semux.info/

**Comment by orogvany** [comment]
It has to be a return value of just the number of SEM, not require scraping a page.

No JSON, no html, just a number as text.

thanks though!

**Comment by orogvany** [comment]
This has been added.
