### ISSUE TITLE
Encode error

### ISSUE THREAD

**Issue by atszgoogle** [semuxproject/semux-core#293]
# 🐛 Bug

(Describe the bug/issue here)
Encoding error

## To reproduce

1.just download “semux-windows-2.1.1-e8314f7.zip“ and install 
2.then you will see picture below

![yu](https://user-images.githubusercontent.com/9426498/81774438-21b01700-951d-11ea-8f46-4c6a7ef9e978.jpg)

## Expected Behavior
(Describe the expected behavior here)

## System information

- Operating system: win 10
- Semux version: 2.1.1

**Comment by tell-1c** [comment]
please, run to _semux-gui.bat_ file.
