### ISSUE TITLE
 has not check commitVotes

### ISSUE THREAD

**Issue by fenghaoming** [semuxproject/semux-core#303]
In the Finalize stage, the number of precommitVotes is checked instead of the number of commitVotes. Does that mean that even if there is no commit stage, as long as timeout triggers enterFinalize, the block will grow? Thank you!

**Comment by tell-1c** [comment]
pls, give a link to code for reference this issue.

**Comment by fenghaoming** [comment]
> pls, give a link to code for reference this issue.

src/main/java/com/fusionbank/blockchain/consensus/bft/BFT.java

```
    protected void enterFinalize() {


        Optional<byte[]> blockHash = precommitVotes.anyApproved();

```

I think here should be commitVotes.anyApproved();

thx!

**Comment by honeycrypto** [comment]
Reopening it, this was not resolved in ec75fc9, but #306

**Comment by fenghaoming** [comment]
> Reopening it, this was not resolved in [ec75fc9](https://github.com/semuxproject/semux-core/commit/ec75fc993b62991e76da0ba00b4266da83a7415d), but #306

I think #306 has not resolved this problem

**Comment by honeycrypto** [comment]
Yup, I ment this commit solved other issue

**Comment by fenghaoming** [comment]
> There are two paths that could lead to `enterFinalize`:
> 
> * When 2/3 of the validators have signalled `COMMIT` vote (see the 2/3 vote check [here](https://github.com/semuxproject/semux-core/blob/ab431cb723deba0552dcf04b1b55670a1960f7a0/src/main/java/org/semux/consensus/SemuxBft.java#L552-L555))
> * Time out after the commit phase (see [this code](https://github.com/semuxproject/semux-core/blob/ab431cb723deba0552dcf04b1b55670a1960f7a0/src/main/java/org/semux/consensus/SemuxBft.java#L587-L589))
> 
> Compared with the original PBFT algorithm, SemuxBFT works as follows:
> 
> ```
> PRE_PREPARE message     -> BFT_PROPOSAL message
> 
> PREPARE message         -> BFT_VOTE message (VALIDATE vote)
> 
> <prepared certificate>  -> 2/3 VALIATE certificate
> 
> COMMIT message          -> BFT_VOTE message (PRECOMMIT vote)
> 
> <commited certificate>  -> 2/3 PRECOMMIT certificate
> 
> Commit state change     -> Broadcast BFT_VOTE message (COMMIT vote)
>                            Wait for 2/3 COMMIT votes or timeout (whichever comes first)
>                            Commit state change
> ```
> 
> As you see, the `COMMIT` votes are mainly for network synchronization purpose. It is not part of the certificates and is not related to `COMMIT` messages in PBFT.

I see. Thank you
