### ISSUE TITLE
Faster syncing

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#31]
After PR #4, the main thing that stops us from even faster syncing is bandwidth usage, where the main breakdown is validator signatures.

Proposed changes:
1) Update the p2p protocol to enable transferring blocks without signatures.
2) Only store signatures of one block per validator set update.

**Comment by orogvany** [comment]
I agree. it should only be used for bulk sync.  Otherwise, a malicious peer could send fake blocks.

**Comment by orogvany** [comment]
Duplicates #46
