### ISSUE TITLE
Error running semux-cli.sh build version 80cc764.

### ISSUE THREAD

**Issue by leolepi** [semuxproject/semux-core#35]
Error when running semux-cli.sh:

 Unrecognized option: --add-opens=java.base/sun.net.dns=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Java 1.8
CentOS 7
maven 3.5.2

**Comment by semuxgo** [comment]
This is a regression bug, and has been fixed by 85a62541ba58b3ddba66b5a89be9e71d99aedd45
