### ISSUE TITLE
Consider using DKG for validator signature

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#38]
Currently, it takes a lot of space/bandwidth to transfer and store validator signatures. Distributed key generation algorithm might help us avoid such cost.

Reference:
- https://en.wikipedia.org/wiki/Distributed_key_generation

**Comment by kaar2** [comment]
Another option is using cosi:
https://tools.ietf.org/id/draft-ford-cfrg-cosi-00.html

I opened an issue in the old repository and there was a link to a github project for reference, I’ll try to find it.

**Comment by semuxgo** [comment]
Closed in favor of #163
