### ISSUE TITLE
Register bip44 number

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#50]
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

For bip44 support we need to assign a number for semux.

Anyone care which num we register?

**Comment by borderline23** [comment]
semux  in binary

01110011 01100101 01101101 01110101 01111000

**Comment by mdodong** [comment]
90817
Date semux first post on bct.

**Comment by semuxgo** [comment]
How about using our genesis hash?

**Comment by orogvany** [comment]
It's a max value of 2^31
they state it in hex and decimal
must start with 1 bit for hardened

some thoughts
0xDEADBEEF (classic funny in hex)
0x8005344 (sem in hex 1337.. kinda.) (decimal: 21316)
0x80008AE (decimal: 2222 nice memorable number)
0xdec0ded (decimal: 99356141)





some thoughts
0xbeefdead

**Comment by borderline23** [comment]
sem in hex

**Comment by gpip** [comment]
btw, it's a requirement that there's a wallet using this before it's added to slip-0044.

0x8073656d (sem with 0x80 prefix)

**Comment by orogvany** [comment]
@gpip Yes, I saw the requirement that there's a wallet using this.  Thanks for the reminder.

I have a lib that uses this currently and supports BIP44.  Currently it only supports regular addresses, but we are extending to use Ed25519.  I'm not sure if their requirement is for full wallet integration or if a library counts, but wanted to be ready :D

**Comment by orogvany** [comment]
Last call for suggested code?  Going with @gpip s suggestion if i do not hear back.  thanks

**Comment by orogvany** [comment]
filed https://github.com/satoshilabs/slips/pull/454

**Comment by orogvany** [comment]
Number accepted/registered
