### ISSUE TITLE
Pick EVM implementations

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#51]
We need to pick which EVM implementation to integrate into Semux.

Originally, we wanted to link the [evmjit](https://github.com/semuxproject/evmc-jni) via JNI. Great progress has been made; the challenging part is that it takes `evmjit` a lot of time in compiling the code while execution is much faster.

Alternatively, I'm considering the [Java implementation of the EVM](https://github.com/ethereum/ethereumj/tree/develop/ethereumj-core/src/main/java/org/ethereum/vm) as well. Non-trivial work will be required to make it work, because it's not standalone.

**Comment by semuxgo** [comment]
My early evaluation of the Java implementation of EVM is not bad, but a lot of tests/optimization will be needed to make it work.

**Comment by orogvany** [comment]
We have picked our VM implementation, so closing
