### ISSUE TITLE
Add developer tab on semux gui

### ISSUE THREAD

**Issue by mdodong** [semuxproject/semux-core#62]
#### System information

Semux version: `v1.3.0`

OS & Version: `Windows 10, Windows 7, Ubuntu 16.04, macOS 10.12.6`

#### Expected behaviour

Add dropdown to show devoper/advanced option
this will show tab to enable running on testnet, saving wallet password on semux.properties, setting API user and password

with a save button to update the semux.properties, create semux-cli launcher etc. that will apply the next time semux is launched, offer restart semux using the new saved options

#### Actual behaviour

Running testnet requires running on cli which many are not comfortable doing, 
API and other option on semux.properties requires a bit of editing and not the most convenient option

**Comment by orogvany** [comment]
Saving/updating prop files usually loses all comments

How about a config option in properties to select network?

**Comment by orogvany** [comment]
Closing in favor of #18
