### ISSUE TITLE
Bug with password

### ISSUE THREAD

**Issue by aslsssa** [semuxproject/semux-core#68]
#### System information

Semux version: `semux-macos-1.3.0-8b4f140`

OS & Version: ` macOS 10.13.6`

#### Expected behaviour

I have a problem with the purse on the macos wallet, it accepts, it does not accept the password.

#### Actual behaviour

Sometimes you need to enter your password several times to enter the wallet. Last time I entered the password 6 times. This problem also exists when changing the password 

#### Steps to reproduce the behaviour

1. Open semux.jar
2. Entering the password (several times) if it is written that the password is incorrect.

**Comment by orogvany** [comment]
Has this reoccurred @aslsssa ?  I think maybe you are just typing it wrong, or maybe adding a space before or after password.

Are you using a non ASCII (latin character) based password with diacritics by any chance?

**Comment by orogvany** [comment]
Please reopen if reoccured
