### ISSUE TITLE
h256 native Implementation differs from MessageDigest

### ISSUE THREAD

**Issue by phash** [semuxproject/semux-core#69]
creating a raw transaction and having nativ sodium support disabled, will result in hashes, that cannot be verified by the hash#256 method

disabling native support on the node will accept the signed transaction!

Create a raw TX from Hash (composed via swagger ui)
```
 val raw =  "0x00031409c5f2794d69717d538bfcc150644f7685945cfa00000002540be40000000000004c4b40000000000000000100000165c4f4f54700"
        val key = Key()
        val tx = Transaction.fromEncoded(Hex.decode0x(raw))
tx.verify() //true -
```
Sending this to a local wallet Swagger UI will result in INVALID_FORMAT

disabling native support in Hash#256 accepts the message

rawTX:  0x20864cf9222ec6bd9930e73da1e03efa2a8e0f85b0accc46b4fdca83270854afd63800031409c5f2794d69717d538bfcc150644f7685945cfa00000002540be40000000000004c4b40000000000000000100000165c4f4f5470060d08289d37d86328282ecce95a4917fe8d6173c9e3990afec88cf59a2d95ab842595d5def3d4d724d2b8326306f622180747c0fee7e03c79c2c8defa14ed73b09db7002d5896e2fa3f53d2ba20602bd5d40980e1b9c1ad6a8b185fc2a8501517d

if you felt this is helpful, my wallet would be happy gaining some SEM :)

**Comment by orogvany** [comment]
in your code you aren't signing the transaction...
you need to sign it before verifying :D  

I was able to successfully validate this with both Native and non native implementations.  So it looks like if you sign the tx, it validates.

**Comment by orogvany** [comment]
Please try running

   ```
     byte[] msg = Bytes.random(100);
        byte[] hash = Hash.h256(msg);
        byte[] nativeHash = Native.h256(msg);
        System.out.println(Arrays.equals(hash,nativeHash));
```

and let me know what it prints

**Comment by phash** [comment]
I disabled native completely. 
I am using Blake2b-256 .. but i will check that.

I sign the tx... Without signing the error message is: not a correct hex string
So its simply signing wrong...

I will check fir blake- iirc it is set to default like in semux.

Pending mgr would accept a signed msg from own wallet- uses the same Algorithm for sig and validate...

**Comment by semuxgo** [comment]
I believe we have compatibility tests between the native and Java BLAKE2b implementation. @phash please update this ticket if get more findings.

**Comment by semuxgo** [comment]
Was running the following unit test, and get consistent behavior with/out native impl.

```java
    @Test
    public void testCompatibility() {
        String raw = "0x00031409c5f2794d69717d538bfcc150644f7685945cfa00000002540be40000000000004c4b40000000000000000100000165c4f4f54700";
        Transaction tx = Transaction.fromEncoded(Hex.decode0x(raw));
        System.out.println(tx.validate(Network.MAINNET));
        Native.disable();
        System.out.println(tx.validate(Network.MAINNET));
    }
```

**Comment by phash** [comment]
Imho, this seems to be my fault... damn... Strings... it was blake2s instead of blake2b...
