### ISSUE TITLE
EVM - If using a contract to transfer funds, receiver does not see transaction

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#74]
If I create a contract that transfers from A->B

I can see that B account now has a balance, but his account history is empty!
We need to figure out how to capture events or internal calls from a contract and make sure they're included in UI transactions panel (and possibly API as well)

**Comment by orogvany** [comment]
The EVM module supports returning internalTransactions.

This is desirable to be able to show these in the UI or on block explorer.

I suggest we keep them in a separate DB, and only store if user has configured this, as it can cause DB size bloat.

We may need to add another API call to get internal transactions by transactionId, to support block chain explorers

**Comment by orogvany** [comment]
@semuxgo how do you imagine this operating?

**Comment by semuxgo** [comment]
Let delegate the function to explorer and hope they can display the internal transactions.

One example is etherscan.io
