### ISSUE TITLE
SEMUX HD WALLET

### ISSUE THREAD

**Issue by borderline23** [semuxproject/semux-core#75]
features:
add a button for auto copy on clipboard the phrase seed.
add also a possibility to use the right click of the mouse for copy the seed.
or add a button fo save the seed on a text file

**Comment by orogvany** [comment]
You should not save your seed to a text file.  Usually wallets disable copy/paste, but we allow it.  I'd prefer not to add special copy button as that would be implicit encouragement to use it.

They are meant to be written down for security

**Comment by orogvany** [comment]
We will be adding instructions as to this above the code
