### ISSUE TITLE
When I created multiple new addresses on the same wallet.dat, the wallet crashed and the new address was lost.

### ISSUE THREAD

**Issue by faith511** [semuxproject/semux-core#78]
I created a new address on the same wallet.dat. This wallet.dat already includes the address I created a long time ago. Then I transferred the new address, everything was fine. After a while, the wallet crashed. When I opened the wallet again, the new address was lost and my SEM was lost. These new addresses are available in the block browser.

**Comment by borderline23** [comment]
why you use an old version of wallet?

**Comment by faith511** [comment]
> why you use an old version of wallet?
> 
> https://github.com/semuxproject/semux-core/releases

No, I use a new wallet, but my wallet.dat is unchanged.

**Comment by orogvany** [comment]
Looks like legacy wallet usage, have verified wallets are persisted before returning back to user.  Please reopen if you see this and can clarify versions.
