### ISSUE TITLE
HD wallet creation should be on welcome screen

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#82]
HD wallet creation/import should be on welcome screen.

We also need to decide on some text to show what it is, and what to do with it.

It's unclear right now that the HD key password can be different than main wallet password.

**Comment by mdodong** [comment]
I suggest we remove the `HD key password` coz this can add confusion to many users

**Comment by Michail1** [comment]
I disagree with regards to removing it; however, I wrote that the term should be changed and/or explanation added on the popup to differentiate the wallet password from the seed encryption password.

**Comment by orogvany** [comment]
I did make them differently named on the cli to see if that clarified.  I'm thinking not calling it a password, but maybe unlock key, or restore key and restore phrase

**Comment by mdodong** [comment]
I think better to call it 
`seed password`

That way it's clear that the password is for the mnemonic seed

**Comment by semuxgo** [comment]
See #231
