### ISSUE TITLE
ERC20 standard support in wallet

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#85]
We should support ERC20 or a modified set of that plus the ERC for contract method inspection.

This should work within the UI eventually.

**Comment by orogvany** [comment]
There has been no feedback about native support for ERC20 type tokens running on semux, so considering this a non-issue.

closing.

**Comment by honeycrypto** [comment]
@orogvany actually, it matters. But I think this has nothing to do with the core functionality or the very next release. We can find the best solution later. 

I'd like to see the core gui and cli wallets as software for validators and dapp developers only. I'm totally against of [Infura-like solutions](https://www.coindesk.com/the-race-is-on-to-replace-ethereums-most-centralized-layer), but we all agree that final consumers should have other light and easy to use clients.
