### ISSUE TITLE
Add respository for Semux Request for Comment (SRC)

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#86]
We may want to consider a new repository for SRCs Semux Request for Comments

So we can get outside proposals or a place for hashing out expectations and specs for features going forward.

**Comment by semuxgo** [comment]
Is this something similar to BIP or EIP?

**Comment by orogvany** [comment]
Yes.  Seems like a good standard to follow.

**Comment by orogvany** [comment]
Looks like one was created. https://github.com/semuxproject/RFPs
