### ISSUE TITLE
Unsupported option - wallet.password

### ISSUE THREAD

**Issue by mdodong** [semuxproject/semux-core#91]
Hi there,

#### System information

Semux version: `semux-linux-1.5.0-RC1-021d510`

OS & Version: `Windows 10`

#### Expected behaviour

run wallet without being asked for the wallet password

#### Actual behaviour

06:38:57.975 ERROR    AbstractConfig   Unsupported option: wallet.password = testnet

#### Steps to reproduce the behaviour

1. copy wallet config from previous release 
`
#================
# Wallet
#================

# This option is only useful in case that you need to automatically unlock your wallet.data file.
# Please ensure that the access permission of semux.properties is properly configured when you put your password here.
# Alternatively SEMUX_WALLET_PASSWORD environment variable can be set for automatic unlock.
wallet.password = testnet
`
2. Run wallet

**Comment by orogvany** [comment]
Hm. Not sure how that went missing. Seems like a case I missed for hd wallet.  Will look into it

**Comment by orogvany** [comment]
Looks like this was never added.  Should remove from docs.  Having 3 ways to set pass seems odd

**Comment by orogvany** [comment]
removed mention of feature in #132
