### ISSUE TITLE
Exception when upgrading the client

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#93]
```
./dist/linux/semux-cli.sh --network testnet --coinbase 2
Please enter your password:
03:02:19.671 ERROR    Wallet           org.bouncycastle.crypto.InvalidCipherTextException: pad block corrupted
```

**Comment by orogvany** [comment]
This is caused by bad password.

Will check if the commandline bad password is not re-queried for.

**Comment by orogvany** [comment]
This works as expected.  bad paper will log the cipher exception.  
Adding exception message as error code alone is not enough
