### ISSUE TITLE
New accounts get random name

### ISSUE THREAD

**Issue by Messier81z** [semuxproject/semux-core#95]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the Discord channel here: https://discord.gg/qQVckKZ

#### System information

Semux version: semux-linux-1.5.0-RC1-021d510.tar.gz

OS & Version: Ubuntu 18.04

#### Expected behaviour

Create new accounts with empty name.

#### Actual behaviour

Creates new accounts with a random characters in the name field. Each new account gets the same random set of characters.

#### Steps to reproduce the behaviour

1. Click on "New Account" and create a new account.

**Comment by orogvany** [comment]
Hi.  This is not a 'random' name.  It is the hd key path.  It's a known standard.  They are all different.  Check the last digit of the account name.  Thanks!

**Comment by orogvany** [comment]
@Messier81z I take your point though.  It looks like our default columns in the UI cut off the end of this new labelling scheme, which is annoying!  I'll fix up the naming path and make sure that our default column width is wide enough to display it so its more clear what the heck you're looking at.

thanks!

**Comment by orogvany** [comment]
Fixed alias creation.  Propose HD wallets be created with 'HD/Semux/0' 'HD/Semux/1' etc for Heirarchical deterministic keys.

Open to other suggestions.  It can be localized into other languages where formatting makes sense.

**Comment by Messier81z** [comment]
Well done, thanks for fixing.
