### ISSUE TITLE
HD wallet from CLI - do we force HD generation on start?

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#99]
I wonder about exchange updating wallet.  Does the startup of CLI on update prompting to create HD key pose a problem to update path for existing wallets?

If I am network admin for an exchange tasked with updating wallet, should I be privy to the HD key backup key/phrase?

Should we allow an option to continue without an HD wallet as default behavior from CLI, and only prompt to create if they try to add a new account from CLI?

**Comment by honeycrypto** [comment]
I think we should move to HD wallets only when we are sure that they are safe to use. While users can still backup their wallet.data, the only official recommended way to backup a wallet should be `seed`.

**Comment by orogvany** [comment]
Depends on #171

**Comment by orogvany** [comment]
Moved to 1.6.0, as it is not required for VM release, no fork required, and we should make sure exchanges are informed/aware.

**Comment by orogvany** [comment]
This has been resolved to be opt in
